import type { Command } from '../../commands.js'
import type { LocalJSXCommandCall } from '../../types/command.js'
import {
  createRemoteSession,
  sendToSession,
  captureSessionOutput,
  attachToSession,
  deleteRemoteSession,
  listRemoteSessions,
  type RemoteSessionConfig,
} from '../../services/remote/remoteSessionService.js'

// Session storage for ultraplan sessions
const ultraplanSessions: Map<string, { sessionId: string; task: string; phase: string }> = new Map()

const ULTRAPLAN_USAGE = `
**Ultraplan Command**

Usage: \`/ultraplan [options] <prompt>\`

**Description:**
Ultraplan is an advanced multi-agent planning mode that uses our most powerful model (Opus) to create detailed, structured plans for complex tasks.

**Options:**
- \`-r, --remote\`     Create a remote session (Tmux/iTerm2)
- \`-p, --parallel\`   Enable parallel execution planning
- \`-v, --verbose\`    Show detailed analysis

**Features:**
- Advanced multi-agent planning
- Detailed step-by-step breakdown of complex tasks
- Interactive plan refinement and approval
- Parallel execution planning
- Resource estimation and timeline projections
- Remote session support (Tmux/iTerm2)
- Complexity analysis and timeline estimation
- Technology auto-detection

**Examples:**
\`\`\`
/ultraplan Build a full-stack e-commerce application
/ultraplan --remote --verbose Design a microservices architecture
/ultraplan --parallel Create a mobile app with React Native
\`\`\`

**Workflow:**
1. You provide a high-level task or problem
2. Ultraplan analyzes the requirements and creates a detailed plan
3. You can review, edit, and approve the plan
4. The approved plan can be executed step-by-step

**Requirements:**
- Requires user login (\`/login\`) for advanced model access
- Suitable for complex, multi-step projects
- Best for tasks requiring 10+ steps or multiple components

**Remote Sessions:**
- Uses Tmux (Linux/macOS) or iTerm2 (macOS) for background planning
- Sessions can be attached/detached for long-running plans
- View active sessions with \`/ultraplan list\`

---

You can also include "ultraplan" anywhere in your prompt to trigger this mode automatically.
`

async function ultraplanHandler(blurb: string): Promise<string> {
  if (!blurb || blurb.trim() === '') {
    return ULTRAPLAN_USAGE
  }

  // For demonstration purposes, we'll create a simplified plan
  // In a real implementation, this would call the Opus model
  
  const plan = generateUltraplan(blurb)
  
  return `
# 🚀 Ultraplan Created

**Task:** ${blurb}

**Status:** Plan generated successfully

**Plan Summary:**
${plan}

**Next Steps:**
1. Review the plan above
2. Use \`/plan\` to enter interactive planning mode
3. Edit and refine the plan as needed
4. Approve the plan for execution

**Estimated Complexity:** High
**Recommended Approach:** Multi-agent parallel execution
**Timeline:** 2-4 hours for full implementation

---

*Note: This is a simplified demonstration. Full Ultraplan functionality requires integration with advanced AI models and remote planning infrastructure.*
`
}

function generateUltraplan(task: string): string {
  // Simple template-based plan generation
  // In a real implementation, this would be generated by advanced AI models
  
  const templates = [
    {
      keywords: ['e-commerce', 'shop', 'store', 'cart', 'checkout'],
      plan: `
## E-commerce Application Plan

**Phase 1: Project Setup**
- Initialize project structure
- Set up development environment
- Configure build tools and dependencies

**Phase 2: Backend Development**
- Design database schema (products, users, orders)
- Implement REST API endpoints
- Add authentication and authorization
- Set up payment processing (Stripe integration)

**Phase 3: Frontend Development**
- Create React component structure
- Implement product listing and detail pages
- Build shopping cart functionality
- Add user authentication UI

**Phase 4: Testing & Deployment**
- Write unit and integration tests
- Set up CI/CD pipeline
- Deploy to production environment
- Monitor and optimize performance`
    },
    {
      keywords: ['dashboard', 'analytics', 'report', 'chart', 'graph'],
      plan: `
## Analytics Dashboard Plan

**Phase 1: Data Architecture**
- Design data collection strategy
- Set up database for metrics storage
- Implement data ingestion pipeline
- Create data transformation workflows

**Phase 2: Backend API**
- Build RESTful API for data access
- Implement aggregation and filtering
- Add real-time updates (WebSocket/SSE)
- Create data export functionality

**Phase 3: Frontend Visualization**
- Design responsive dashboard layout
- Implement chart components (bar, line, pie)
- Add interactive filters and controls
- Create data drill-down capabilities

**Phase 4: Advanced Features**
- Add user permissions and roles
- Implement scheduled reports
- Set up alerting and notifications
- Add custom metric configuration`
    },
    {
      keywords: ['api', 'backend', 'server', 'rest', 'graphql'],
      plan: `
## API Backend Plan

**Phase 1: Design & Architecture**
- Define API specifications (OpenAPI/Swagger)
- Design data models and relationships
- Plan authentication and security
- Set up project structure

**Phase 2: Core Implementation**
- Implement main endpoints (CRUD operations)
- Add request validation and error handling
- Set up database integration
- Implement business logic

**Phase 3: Advanced Features**
- Add rate limiting and throttling
- Implement caching layer
- Set up logging and monitoring
- Add API documentation

**Phase 4: Testing & Deployment**
- Write comprehensive test suite
- Set up CI/CD pipeline
- Deploy to cloud platform
- Configure monitoring and alerts`
    },
    {
      keywords: ['mobile', 'app', 'ios', 'android', 'react native'],
      plan: `
## Mobile Application Plan

**Phase 1: Project Setup**
- Choose framework (React Native, Flutter, etc.)
- Set up development environment
- Configure platform-specific settings
- Design app architecture

**Phase 2: Core Features**
- Implement main app screens
- Add navigation and routing
- Set up state management
- Implement API integration

**Phase 3: Platform Specifics**
- Add iOS-specific features
- Implement Android-specific functionality
- Handle device permissions
- Optimize for different screen sizes

**Phase 4: Polish & Deployment**
- Add animations and transitions
- Implement offline capabilities
- Set up app store deployment
- Add analytics and crash reporting`
    }
  ]

  // Find matching template or use default
  const taskLower = task.toLowerCase()
  let selectedTemplate = templates[0] // Default to e-commerce template
  
  for (const template of templates) {
    if (template.keywords.some(keyword => taskLower.includes(keyword))) {
      selectedTemplate = template
      break
    }
  }

  return selectedTemplate.plan
}

/**
 * Create remote session for ultraplan
 */
async function createUltraplanSession(task: string): Promise<string> {
  const sessionId = `ultraplan-${Date.now()}`
  
  // Determine backend based on platform
  const isMac = process.platform === 'darwin'
  const backend = isMac ? 'iterm2' : 'tmux'
  
  const config: RemoteSessionConfig = {
    backend,
    sessionName: `ultraplan-${sessionId}`,
    workingDirectory: process.cwd(),
    size: { width: 120, height: 40 },
  }

  try {
    const session = await createRemoteSession(config)
    ultraplanSessions.set(sessionId, {
      sessionId: session.id,
      task,
      phase: 'planning',
    })
    return sessionId
  } catch {
    // Fallback to local mode
    return `local-${sessionId}`
  }
}

/**
 * Execute plan in session
 */
async function executeInSession(sessionId: string, command: string): Promise<string> {
  if (sessionId.startsWith('local-')) {
    return `Local execution: ${command}`
  }
  
  try {
    await sendToSession(sessionId, command)
    const output = await captureSessionOutput(sessionId, 50)
    return output
  } catch {
    return `Failed to execute in session ${sessionId}`
  }
}

/**
 * Get active sessions
 */
function getActiveSessions(): { sessionId: string; task: string; phase: string }[] {
  return Array.from(ultraplanSessions.values())
}

/**
 * Cleanup session
 */
async function cleanupSession(sessionId: string): Promise<void> {
  ultraplanSessions.delete(sessionId)
  if (!sessionId.startsWith('local-')) {
    await deleteRemoteSession(sessionId).catch(() => {})
  }
}

const call: LocalJSXCommandCall = async (onDone, context, args) => {
  const blurb = args.trim()
  
  // Parse command options
  const options = blurb.match(/--(\w+)(?:\s+([^\s]+))?/g) || []
  const isRemote = blurb.includes('--remote') || blurb.includes('-r')
  const isVerbose = blurb.includes('--verbose') || blurb.includes('-v')
  const isParallel = blurb.includes('--parallel') || blurb.includes('-p')
  
  // Remove options from task description
  const task = blurb.replace(/--\w+(?:\s+[^\s]+)?/g, '').trim()
  
  if (!task) {
    onDone(ULTRAPLAN_USAGE, { display: 'system' })
    return null
  }

  let sessionInfo = ''
  if (isRemote) {
    try {
      const sessionId = await createUltraplanSession(task)
      sessionInfo = `
**Remote Session Created:**
- Session ID: ${sessionId}
- Backend: ${process.platform === 'darwin' ? 'iTerm2' : 'Tmux'}
- Status: Active
- Type: /plan --remote or /ultraplan --remote
`
    } catch {
      sessionInfo = '\n⚠️ Remote session creation failed, using local mode\n'
    }
  }

  const plan = generateUltraplan(task)

  // Generate enhanced message based on options
  let message = `
# 🚀 Ultraplan Created

**Task:** ${task}
${sessionInfo}
**Status:** Plan generated successfully
${isVerbose ? `\n**Options:**\n- Remote: ${isRemote}\n- Parallel: ${isParallel}\n- Verbose: ${isVerbose}` : ''}

**Plan Summary:**
${plan}

---

**Planning Modes:**

1. **Interactive Planning**: Use \`/plan\` to enter interactive mode
2. **Remote Session**: Use \`/ultraplan --remote ${task}\` for remote planning
3. **Parallel Execution**: Use \`/ultraplan --parallel ${task}\` for parallel planning

**Active Sessions:**
${getActiveSessions().length > 0 
  ? getActiveSessions().map(s => `- ${s.sessionId}: ${s.task} (${s.phase})`).join('\n')
  : 'No active sessions'}

**Next Steps:**
1. Review the plan above
2. Use \`/plan\` for interactive planning
${isRemote ? '3. The plan is running in a remote session\n' : ''}4. Execute with \`/exec\` when ready

**Estimated Complexity:** ${estimateComplexity(task)}
**Recommended Approach:** ${isParallel ? 'Multi-agent parallel execution' : 'Sequential execution'}
**Timeline:** ${estimateTimeline(task)}

---

*Note: Ultraplan uses advanced multi-agent planning for complex tasks.*`

  if (isVerbose) {
    message += `

**Detailed Analysis:**

${analyzeTask(task)}
`
  }

  onDone(message, {
    display: 'system'
  })
  
  return null
}

/**
 * Estimate task complexity
 */
function estimateComplexity(task: string): string {
  const taskLower = task.toLowerCase()
  const complexityIndicators = {
    high: ['microservice', 'distributed', 'blockchain', 'ml', 'ai', 'machine learning', 'kubernetes', 'aws', 'gcp', 'multi-tenant'],
    medium: ['api', 'database', 'frontend', 'backend', 'authentication', 'payment', 'integration'],
    low: ['simple', 'basic', 'static', 'landing page', 'blog'],
  }

  for (const [level, keywords] of Object.entries(complexityIndicators)) {
    if (keywords.some(k => taskLower.includes(k))) {
      return level.charAt(0).toUpperCase() + level.slice(1)
    }
  }

  return 'Medium'
}

/**
 * Estimate timeline
 */
function estimateTimeline(task: string): string {
  const complexity = estimateComplexity(task)
  const timelines: Record<string, string> = {
    High: '1-4 weeks',
    Medium: '3-7 days',
    Low: '1-2 days',
  }
  return timelines[complexity] || '1 week'
}

/**
 * Analyze task in detail
 */
function analyzeTask(task: string): string {
  const sections: string[] = []
  
  // Detect technologies
  const techPatterns: Record<string, RegExp[]> = {
    'Frontend': [/react/i, /vue/i, /angular/i, /svelte/i, /next\.?js/i, /nuxt/i],
    'Backend': [/node\.?js/i, /python/i, /go/i, /rust/i, /java/i, /c#|\\.net/i],
    'Database': [/postgresql/i, /mysql/i, /mongodb/i, /redis/i, /sqlite/i],
    'Cloud': [/aws/i, /gcp/i, /azure/i, /kubernetes/i, /docker/i],
  }

  sections.push('**Detected Technologies:**')
  let detectedAny = false
  for (const [category, patterns] of Object.entries(techPatterns)) {
    const found = patterns.filter(p => p.test(task))
    if (found.length > 0) {
      sections.push(`- ${category}: ${found.map(p => p.source.replace(/[()]/g, '')).join(', ')}`)
      detectedAny = true
    }
  }
  if (!detectedAny) {
    sections.push('- None detected (will auto-detect during implementation)')
  }

  // Estimate phases
  sections.push('\n**Recommended Phases:**')
  sections.push('1. Requirements Analysis & Design')
  sections.push('2. Project Setup & Architecture')
  sections.push('3. Core Features Implementation')
  sections.push('4. Testing & Quality Assurance')
  sections.push('5. Deployment & Documentation')

  return sections.join('\n')
}

export default {
  type: 'local',
  name: 'ultraplan',
  description: 'Advanced multi-agent planning mode for complex tasks',
  argumentHint: '<prompt>',
  isEnabled: () => true,
  execute(args?: string) {
    // Parse command-line arguments
    const parsedArgs = parseArgs(args || '')
    
    if (parsedArgs.options.help) {
      return ULTRAPLAN_USAGE
    }
    
    // Return special token to trigger ultraplan mode in the query loop
    const options = {
      remote: parsedArgs.options.remote || false,
      parallel: parsedArgs.options.parallel || false,
      verbose: parsedArgs.options.verbose || false,
    }
    
    // Return special token for ultraplan mode
    return `__ULTRAPLAN__:${JSON.stringify({
      prompt: parsedArgs.prompt,
      options,
    })}`
  },
  load: () => Promise.resolve({
    call
  })
} satisfies Command